[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npx prisma generate", "npx prisma migrate deploy", "npm run build"]

[start]
cmd = "npm run start"

[variables]
NPM_CONFIG_PRODUCTION = "false"
